spring:
  jpa:
    show-sql: true
    generate-ddl: true

  hibernate:
    ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password: admin
    url: jdbc:h2:mem:testdb

server:
  port: 8080
